services:
  - name: server
    plan: free
    type: web
    env: node
    repo: https://github.com/daaimah123/2024H2FinalProjectTemplateRender
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: DATABASE_URI
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: db
    plan: free
    ipAllowList: []
